require("piero.plugins-setup")
require("piero.core.options")
require("piero.core.keymaps")
require("piero.core.colorscheme")
require("piero.plugins.comment") 
require("piero.plugins.nvim-tree") 
require("piero.plugins.telescope") 
